name: pitchbook
description: "Karma Group Pitchbook App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.9+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dotted_line: ^3.2.2
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.3
  font_awesome_flutter: ^10.9.1
  http: ^1.2.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  svg_clip: ^0.0.2
  url_launcher: ^6.3.0
  video_player: ^2.10.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/community/
    - assets/interface/
    - assets/json/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Playfair
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/playfair/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/playfair/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/playfair/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/playfair/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Eloquent
      fonts:
        - asset: assets/fonts/eloquent/EloquentJFRegularPro.ttf
          weight: 400
        - asset: assets/fonts/eloquent/EloquentJFItalicPro.ttf
          weight: 400
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
